const lessonData = {};

lessonData["01_Ponzi.mp3"] = [{
    text: "1. Charles Ponzi. Charles Ponzi ist einer der berühmtesten Betrüger der Geschichte. Sein Name wird heute für eine besondere Art von Verbrechen verwendet: das „Ponzi-Schema“. Im Jahr 1920 kam er nach Amerika, um ein besseres Leben zu finden. Er erzählte den Leuten, er habe eine geheime Methode, um sie sehr schnell sehr reich zu machen. Er versprach ihnen in nur 90 Tagen eine Menge Extra-Geld. Viele normale Menschen gaben ihm ihre gesamten Ersparnisse, weil sie reich werden wollten. Aber Ponzi hatte kein echtes Geschäft. Er log alle an. Er nahm einfach Geld von neuen Investoren und zahlte es an die älteren aus. Den Rest des Geldes verwendete er für schicke Anzüge, teure Schuhe und große Häuser für sich selbst. Die Leute hielten ihn für ein Genie im Geschäft. Schließlich untersuchte ein Zeitungsreporter sein Unternehmen und deckte die schreckliche Wahrheit auf. Die Polizei verhaftete ihn sofort, und seine Investoren verloren zwanzig Millionen Dollar. Er kam für viele Jahre ins dunkle Gefängnis. Am Ende starb er als armer Mann, aber sein krimineller Name ist bis heute weltberühmt.",
    dict: { "berühmtesten":"en ünlü", "betrüger":"dolandırıcı", "geschichte":"tarih", "verbrechen":"suç", "verwendet":"kullanılır", "geheime":"gizli", "methode":"yöntem", "schnell":"hızlı", "reich":"zengin", "versprach":"söz verdi", "menge":"miktar", "normale":"normal", "gesamten":"tüm", "ersparnisse":"tasarruflar", "echtes":"gerçek", "geschäft":"iş", "log":"yalan söyledi", "neuen":"yeni", "investoren":"yatırımcılar", "zahlte":"ödedi", "älteren":"daha eski", "aus":"dışarı/geri", "verwendete":"kullandı", "schicke":"şık", "anzüge":"takım elbiseler", "teure":"pahalı", "schuhe":"ayakkabılar", "häuser":"evler", "hielten":"tuttular/sandılar", "genie":"deha", "untersuchte":"inceledi", "zeitungsreporter":"gazete muhabiri", "deckte":"açığa çıkardı", "wahrheit":"gerçek", "verhaftete":"tutukladı", "sofort":"hemen", "verloren":"kaybettiler", "zwanzig":"yirmi", "millionen":"milyon", "dunkle":"karanlık", "gefängnis":"hapishane", "starb":"öldü", "armer":"fakir", "krimineller":"suçlu", "weltberühmt":"dünya çapında ünlü" },
    questions: [ {q:"Kam Charles Ponzi im Jahr 1920 nach Amerika?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er ein echtes Geschäft mit Fabriken?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zahlte er alte Investoren mit dem Geld von neuen Investoren?", a_de:"Ja", a_tr:"Evet"}, {q:"Kaufte er sich von dem Geld schicke Anzüge und teure Schuhe?", a_de:"Ja", a_tr:"Evet"}, {q:"Deckte ein Polizist die Wahrheit auf?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verloren die Investoren zwanzig Millionen Dollar?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb Ponzi am Ende als sehr reicher Mann?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["02_Lustig.mp3"] = [{
    text: "2. Victor Lustig. Victor Lustig war ein sehr cleverer und hochgefährlicher Hochstapler. Im Jahr 1925 las er einen Zeitungsartikel, der besagte, dass der berühmte Eiffelturm in Paris teure Reparaturen brauche. Er hatte eine geniale und verrückte Idee. Er fälschte Regierungspapiere und lud reiche Metallhändler zu einem geheimen Treffen in einem Hotel ein. Er erzählte ihnen, die Stadt sei zu arm und wolle den Eiffelturm als Schrott verkaufen! Er war so höflich, so gut gekleidet und sprach so selbstbewusst, dass ein Geschäftsmann ihm die große Lüge glaubte. Der Mann gab Lustig einen riesigen Koffer voller Bargeld. Lustig nahm das schwere Geld und floh schnell mit dem Zug nach Österreich. Der Käufer war zu peinlich berührt und schämte sich, der Polizei von seinem dummer Fehler zu erzählen. Lustig war so erfolgreich, dass er später tatsächlich nach Paris zurückkehrte und versuchte, den berühmten Turm ein zweites Mal zu verkaufen! Schließlich erwischten ihn die amerikanischen Behörden wegen Falschgeldherstellung. Ein Richter schickte ihn ins berühmte Inselgefängnis Alcatraz. Dort starb er, aber die Leute erzählen sich bis heute Geschichten von seinem unglaublichen Eiffelturm-Trick.",
    dict: { "cleverer":"zeki", "hochgefährlicher":"son derece tehlikeli", "hochstapler":"sahtekar", "besagte":"belirten", "reparaturen":"onarımlar", "brauche":"ihtiyacı olduğunu", "verrückte":"çılgın", "idee":"fikir", "fälschte":"sahtesini yaptı", "regierungspapiere":"hükümet belgeleri", "lud":"davet etti", "metallhändler":"metal tüccarları", "geheimen":"gizli", "treffen":"toplantı", "hotel":"otel", "arm":"fakir", "schrott":"hurda", "verkaufen":"satmak", "höflich":"kibar", "gekleidet":"giyimli", "selbstbewusst":"özgüvenli", "geschäftsmann":"iş adamı", "lüge":"yalan", "glaubte":"inandı", "riesigen":"devasa", "koffer":"valiz", "bargeld":"nakit para", "floh":"kaçı", "zug":"tren", "österreich":"avusturya", "käufer":"alıcı", "peinlich":"utanç verici", "berührt":"etkilenmiş", "schämte":"utandı", "fehler":"hata", "erfolgreich":"başarılı", "tatsächlich":"aslında", "zweites":"ikinci", "erwischten":"yakaladılar", "behörden":"yetkililer", "falschgeldherstellung":"sahte para üretimi", "richter":"hakim", "inselgefängnis":"ada hapishanesi" },
    questions: [ {q:"Wollte Victor Lustig den Eiffelturm verkaufen?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte die Stadt Paris den Turm wirklich als Schrott verkaufen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Glaubte ein Metallhändler die Lüge?", a_de:"Ja", a_tr:"Evet"}, {q:"Floh Lustig mit einem Koffer voller Bargeld nach Österreich?", a_de:"Ja", a_tr:"Evet"}, {q:"Ging der Käufer sofort zur Polizei?", a_de:"Nein", a_tr:"Hayır"}, {q:"Versuchte Lustig den Turm ein zweites Mal zu verkaufen?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb Lustig im Gefängnis Alcatraz?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["03_Abagnale.mp3"] = [{
    text: "3. Frank Abagnale Jr. Frank Abagnale Jr. begann sein langes kriminelles Leben schon als junger Teenager. Er rannte von zu Hause weg und merkte schnell, dass er Menschen sehr leicht täuschen konnte. Zuerst tat er so, als wäre er ein echter Pilot. Er kaufte eine gefälschte Pilotenuniform und flog kostenlos mit großen Flugzeugen um die ganze Welt. Dann wechselte er den Beruf. Er gab sich als kluger Arzt in einem Krankenhaus und als seriöser Anwalt vor Gericht aus. Er hatte keine Ausbildung für diese Jobs. Er war einfach sehr intelligent, selbstbewusst und ein toller Schauspieler, sodass alle seine Lügen glaubten. Außerdem machte er Millionen Dollar mit gefälschten Schecks. Das gestohlene Geld gab er für teures Essen und schöne Hotels aus. Die Polizei jagte ihn jahrelang durch viele Länder. Schließlich erwischten sie ihn in Frankreich, wo er sich versteckte. Nach einer Zeit im dunklen Gefängnis gab ihm die Regierung einen besonderen Job. Er begann, für die Polizei zu arbeiten, um andere Betrüger zu fangen. Seine verrückte und spannende Lebensgeschichte wurde zu einem sehr berühmten Film namens „Catch Me If You Can“.",
    dict: { "langes":"uzun", "kriminelles":"suç dolu", "teenager":"genç", "rannte":"koştu", "hause":"ev", "merkte":"fark etti", "täuschen":"kandırmak", "konnte":"bildi", "zuerst":"önce", "tat":"yaptı/davrandı", "echter":"gerçek", "pilot":"pilot", "gefälschte":"sahte", "uniform":"üniforma", "kostenlos":"ücretsiz", "flugzeugen":"uçaklar", "welt":"dünya", "wechselte":"değiştirdi", "beruf":"meslek", "kluger":"zeki", "arzt":"doktor", "krankenhaus":"hastane", "seriöser":"ciddi/saygın", "anwalt":"avukat", "gericht":"mahkeme", "ausbildung":"eğitim", "jobs":"işler", "intelligent":"zeki", "schauspieler":"oyuncu", "schecks":"çekler", "gestohlene":"çalınmış", "essen":"yemek", "schöne":"güzel", "jagte":"kovaladı", "länder":"ülkeler", "frankreich":"fransa", "versteckte":"gizlendi", "regierung":"hükümet", "besonderen":"özel", "fangen":"yakalamak", "spannende":"heyecanlı", "film":"film" },
    questions: [ {q:"Begann Frank sein kriminelles Leben als Kind?", a_de:"Nein", a_tr:"Hayır"}, {q:"Tat er so, als wäre er ein Pilot?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er eine Ausbildung als Arzt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Machte er Millionen mit gefälschten Schecks?", a_de:"Ja", a_tr:"Evet"}, {q:"Erwischte die Polizei ihn in Frankreich?", a_de:"Ja", a_tr:"Evet"}, {q:"Arbeitete er später für die Polizei?", a_de:"Ja", a_tr:"Evet"}, {q:"Heißt der berühmte Film über ihn „Catch Me If You Can“?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["04_Sorokin.mp3"] = [{
    text: "4. Anna Sorokin. Anna Sorokin war eine junge Frau aus Russland, die sich in New York City ein komplett gefälschtes und glamouröses Leben erfand. Sie änderte ihren Namen in Anna Delvey. Sie erzählte allen, sie sei eine sehr reiche Deutsche mit Millionen auf dem Familienkonto. Sie trug teure Designer-Kleidung, wohnte in den besten Luxushotels und aß in den berühmtesten Restaurants. Sie war sehr gut darin, wie eine reiche, wichtige und beschäftigte Person zu wirken. Sie täuschte ihre reichen Freunde, große Banken und schicke Hotels, damit sie für ihren teuren Lebensstil zahlten. Sie versuchte sogar, einen Kredit über 22 Millionen Dollar von einer großen Bank zu bekommen, um einen gefälschten Kunstclub für Reiche zu gründen. Schließlich merkten ihre Freunde, dass sie ihr Geld nie zurückzahlte. Die Luxushotels riefen die Polizei, weil sie ihre hohen Rechnungen nicht bezahlte. Die Polizei verhaftete sie 2017, und ein Richter schickte sie ins Gefängnis. Ihre verrückte Geschichte wurde kürzlich zu einer sehr populären Fernsehserie, die weltweit viele Menschen sahen.",
    dict: { "russland":"rusya", "erfand":"icat etti", "änderte":"değiştirdi", "reiche":"zengin", "deutsche":"alman", "familienkonto":"aile hesabı", "trug":"giydi", "designer-kleidung":"tasarımcı kıyafeti", "wohnte":"yaşadı/kaldı", "luxushotels":"lüks oteller", "restaurants":"restoranlar", "wichtige":"önemli", "beschäftigte":"meşgul", "person":"kişi", "wirken":"görünmek", "täuschte":"kandırdı", "freunde":"arkadaşlar", "banken":"bankalar", "lebensstil":"yaşam tarzı", "zahlten":"ödediler", "versuchte":"denedi", "kredit":"kredi", "bekommen":"almak", "kunstclub":"sanat kulübü", "gründen":"kurmak", "merkten":"fark ettiler", "zurückzahlte":"geri ödedi", "riefen":"çağırdılar", "hohen":"yüksek", "rechnungen":"faturalar", "bezahlte":"ödedi", "verhaftete":"tutukladı", "richter":"hakim", "fernsehserie":"televizyon dizisi", "weltweit":"dünya çapında" },
    questions: [ {q:"Ist Anna Sorokin eine echte reiche Deutsche?", a_de:"Nein", a_tr:"Hayır"}, {q:"Lebte sie in New York City?", a_de:"Ja", a_tr:"Evet"}, {q:"Trug sie teure Designer-Kleidung?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte sie 22 Millionen Dollar von einer Bank?", a_de:"Ja", a_tr:"Evet"}, {q:"Zahlte sie ihren Freunden immer das Geld zurück?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde sie im Jahr 2017 verhaftet?", a_de:"Ja", a_tr:"Evet"}, {q:"Gibt es eine Fernsehserie über ihre Geschichte?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["05_Madoff.mp3"] = [{
    text: "5. Bernie Madoff. Bernie Madoff beging das größte und schlimmste Finanzverbrechen der Weltgeschichte. Viele Jahre lang war er ein hoch angesehener und berühmter Geschäftsmann in New York. Die Leute vertrauten ihm völlig, weil er ehrlich, ruhig und erfolgreich wirkte. Er versprach, dass er ihr Geld in den Aktienmarkt investieren und sie viel reicher machen würde. Tausende Menschen, darunter berühmte Filmschauspieler und große Wohltätigkeitsorganisationen für Arme, gaben ihm ihre gesamten Ersparnisse. Aber Madoff investierte das Geld nicht. Genau wie Charles Ponzi nutzte er ein gefälschtes System. Er zahlte einfach mit neuem Geld die alten Investoren aus. Er stahl etwa 65 Milliarden Dollar! Im Jahr 2008 brach die Weltwirtschaft zusammen. Zu viele Leute wollten gleichzeitig ihr Geld zurück, und Madoff konnte nicht zahlen. Er erzählte schließlich seinen beiden Söhnen die schreckliche Wahrheit, und sie riefen sofort die Polizei. Der Richter war sehr wütend und verurteilte ihn zu 150 Jahren Gefängnis. Er starb im Gefängnis als zutiefst gehasster Mann.",
    dict: { "beging":"işledi", "größte":"en büyük", "schlimmste":"en kötü", "finanzverbrechen":"finansal suç", "hoch":"yüksek", "angesehener":"saygın", "vertrauten":"güvendiler", "völlig":"tamamen", "ehrlich":"dürüst", "ruhig":"sakin", "aktienmarkt":"borsa", "darunter":"aralarında", "filmschauspieler":"film oyuncuları", "wohltätigkeitsorganisationen":"hayır kurumları", "arme":"fakirler", "system":"sistem", "stahl":"çaldı", "milliarden":"milyar", "brach":"kırıldı/çöktü", "weltwirtschaft":"dünya ekonomisi", "zusammen":"birlikte (çökmek)", "gleichzeitig":"aynı anda", "zahlen":"ödemek", "schließlich":"sonunda", "söhnen":"oğullar", "schreckliche":"korkunç", "wütend":"kızgın", "verurteilte":"mahkum etti", "gehasster":"nefret edilen" },
    questions: [ {q:"War Bernie Madoff ein berühmter Geschäftsmann in New York?", a_de:"Ja", a_tr:"Evet"}, {q:"Investierte er das Geld wirklich in den Aktienmarkt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Stahl er etwa 65 Milliarden Dollar?", a_de:"Ja", a_tr:"Evet"}, {q:"Brach die Weltwirtschaft im Jahr 2008 zusammen?", a_de:"Ja", a_tr:"Evet"}, {q:"Riefen seine Söhne die Polizei?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er zu 150 Jahren Gefängnis verurteilt?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb er als reicher Mann in seinem Haus?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["06_Holmes.mp3"] = [{
    text: "6. Elizabeth Holmes. Elizabeth Holmes war eine junge Studentin, die die Uni abbrach, um ein neues Medizinunternehmen namens Theranos zu gründen. Sie trug immer schwarze Hemden und sprach mit einer seltsamen, tiefen Stimme, um ernst und klug zu wirken. Sie erzählte der Welt, ihr Unternehmen habe eine magische medizinische Maschine erfunden. Diese kleine Maschine könne mit nur einem winzigen Tropfen Blut aus dem Finger Hunderte gefährlicher Krankheiten testen. Reiche Investoren dachten, diese Erfindung würde die Welt verändern, und gaben ihr Milliarden Dollar. Sie wurde sehr berühmt und landete auf den Titelseiten vieler wichtiger Magazine. Es gab nur ein großes Problem: Die Maschine funktionierte überhaupt nicht. Sie war komplett gefälscht. Sie log ihre reichen Investoren, kluge Ärzte und kranke Patienten an, die echte Hilfe brauchten. Schließlich deckte ein mutiger Zeitungsreporter ihr dunkles Geheimnis auf und schrieb einen langen Artikel über ihre schrecklichen Lügen. Ihr großes Unternehmen schloss schnell. Ein Richter schickte sie für elf Jahre ins Gefängnis, weil sie viele kranke Menschen in große Gefahr brachte, um reich und berühmt zu werden.",
    dict: { "uni":"üniversite", "abbrach":"bıraktı/yarıda kesti", "medizinunternehmen":"tıp şirketi", "namens":"adında", "hemden":"gömlekler", "seltsamen":"tuhaf", "tiefen":"derin", "stimme":"ses", "ernst":"ciddi", "klug":"zeki", "magische":"sihirli", "medizinische":"tıbbi", "maschine":"makine", "erfunden":"icat etti", "winzigen":"minicik", "tropfen":"damla", "blut":"kan", "finger":"parmak", "krankheiten":"hastalıklar", "testen":"test etmek", "erfindung":"buluş", "verändern":"değiştirmek", "titelseiten":"manşetler/kapak sayfaları", "magazine":"dergiler", "problem":"problem", "funktionierte":"çalıştı", "kranke":"hasta", "patienten":"hastalar", "hilfe":"yardım", "brauchten":"ihtiyaç duydular", "mutiger":"cesur", "geheimnis":"sır", "schloss":"kapandı", "gefahr":"tehlike", "brachte":"getirdi" },
    questions: [ {q:"Brach Elizabeth Holmes die Universität ab?", a_de:"Ja", a_tr:"Evet"}, {q:"Hieß ihr Unternehmen Theranos?", a_de:"Ja", a_tr:"Evet"}, {q:"Konnte die Maschine wirklich Krankheiten testen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Gaben Investoren ihr Milliarden Dollar?", a_de:"Ja", a_tr:"Evet"}, {q:"War die Maschine komplett gefälscht?", a_de:"Ja", a_tr:"Evet"}, {q:"Schrieb ein Zeitungsreporter über ihre Lügen?", a_de:"Ja", a_tr:"Evet"}, {q:"Schickte der Richter sie für 50 Jahre ins Gefängnis?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["07_MacGregor.mp3"] = [{
    text: "7. Gregor MacGregor. Gregor MacGregor war ein schottischer Soldat, der eine der unglaublichsten und grausamsten Lügen der Geschichte erfand. Im Jahr 1821 kehrte er nach Großbritannien zurück und erzählte den Leuten, er sei der Prinz eines neuen Landes namens Poyais. Er sagte, Poyais sei ein wunderschönes, reiches und friedliches Land in Mittelamerika. Er zeigte bunte Zeichnungen schöner Städte, detaillierte Karten und sogar gefälschtes Geld für dieses perfekte Land. Er sagte, das Wetter sei immer warm und in den Flüssen liege überall gelbes Gold. Viele Briten glaubten seiner wunderbaren Geschichte und kauften leeres Land von ihm. Sie packten ihre Koffer, verließen ihre Häuser und segelten über den gefährlichen Ozean in dieses tolle Paradies. Aber als sie ankamen, gab es keine schöne Stadt. Es gab nur dunklen, wilden und gefährlichen Dschungel. Das perfekte Land Poyais existierte gar nicht! Die meisten armen Leute wurden sehr krank und starben im Dschungel. MacGregor floh mit all ihrem Geld und wurde nie von der Polizei für sein schreckliches und tödliches Verbrechen bestraft.",
    dict: { "schottischer":"iskoç", "soldat":"asker", "grausamsten":"en zalim", "kehrte":"döndü", "großbritannien":"büyük britanya", "prinz":"prens", "landes":"ülke", "wunderschönes":"çok güzel", "friedliches":"huzurlu", "mittelamerika":"orta amerika", "bunte":"renkli", "zeichnungen":"çizimler", "städte":"şehirler", "detaillierte":"detaylı", "karten":"haritalar", "perfekte":"mükemmel", "wetter":"hava durumu", "warm":"sıcak", "flüssen":"nehirler", "liege":"duruyor/var", "gelbes":"sarı", "gold":"altın", "briten":"ingilizler", "wunderbaren":"harika", "leeres":"boş", "verließen":"terk ettiler", "segelten":"yelken açtılar", "ozean":"okyanus", "tolle":"harika", "paradies":"cennet", "ankamen":"vardılar", "wilden":"vahşi", "dschungel":"orman", "existierte":"var oldu", "bestraft":"cezalandırıldı" },
    questions: [ {q:"War Gregor MacGregor ein schottischer Soldat?", a_de:"Ja", a_tr:"Evet"}, {q:"Hieß das neue Land Poyais?", a_de:"Ja", a_tr:"Evet"}, {q:"Gab es in Poyais wirklich Städte und Gold?", a_de:"Nein", a_tr:"Hayır"}, {q:"Segelten die Menschen über den Ozean nach Poyais?", a_de:"Ja", a_tr:"Evet"}, {q:"Fanden sie ein tolles Paradies?", a_de:"Nein", a_tr:"Hayır"}, {q:"Sind viele Menschen im Dschungel gestorben?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde MacGregor von der Polizei bestraft?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["08_Demara.mp3"] = [{
    text: "8. Ferdinand Waldo Demara. Ferdinand Waldo Demara wurde „Der Große Hochstapler“ genannt. Er war ein seltsamer Mann, der es liebte, andere Personen zu sein. Meist wollte er kein Geld stehlen; er wollte sich nur wichtig und respektiert fühlen. In seinem langen Leben gab er sich als stiller Mönch, harter Gefängniswärter, kluger Universitätslehrer und seriöser Anwalt aus. Sein berühmtester Trick passierte während des schwierigen Koreakriegs. Er stahl die Identität eines echten Arztes und trat als Schiffsarzt in die kanadische Marine ein. Er hatte absolut keine medizinische Ausbildung, las aber dicke medizinische Bücher blitzschnell in seiner Kabine. Erstaunlicherweise führte er echte, gefährliche Operationen an schwer verletzten Soldaten durch und rettete ihr Leben! Als der echte Arzt von der Lüge erfuhr, schickte die Marine Demara sofort nach Hause. Die Militärführer waren zu peinlich berührt, ihn ins Gefängnis zu stecken, weil er den Soldaten wirklich geholfen hatte. Er wechselte weiter Namen und Identitäten bis zu seinem Tod. Er führte ein sehr einsames, aber aufregendes Leben, immer als jemand anderes.",
    dict: { "genannt":"adlandırıldı", "seltsamer":"tuhaf", "meist":"çoğunlukla", "stehlen":"çalmak", "wichtig":"önemli", "respektiert":"saygı duyulan", "fühlen":"hissetmek", "stiller":"sessiz", "mönch":"keşiş", "harter":"sert", "gefängniswärter":"gardiyan", "universitätslehrer":"üniversite öğretmeni", "passierte":"oldu/gerçekleşti", "schwierigen":"zor", "koreakriegs":"kore savaşı", "identität":"kimlik", "schiffsarzt":"gemi doktoru", "kanadische":"kanada", "marine":"donanma", "tritt":"girdi/katıldı (trat ein)", "absolut":"kesinlikle", "dicke":"kalın", "bücher":"kitaplar", "blitzschnell":"yıldırım hızıyla", "kabine":"kabin", "operationen":"ameliyatlar", "verletzten":"yaralı", "rettete":"kurtardı", "erfuhr":"öğrendi", "militärführer":"askeri liderler", "einsames":"yalnız", "aufregendes":"heyecan verici" },
    questions: [ {q:"Wollte Demara meistens viel Geld stehlen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Gab er sich als Mönch und Gefängniswärter aus?", a_de:"Ja", a_tr:"Evet"}, {q:"Stahl er die Identität eines Arztes?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er eine echte medizinische Ausbildung?", a_de:"Nein", a_tr:"Hayır"}, {q:"Rettete er Soldaten durch echte Operationen?", a_de:"Ja", a_tr:"Evet"}, {q:"Wurde er von der Marine ins Gefängnis gesteckt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wechselte er seine Identität bis zu seinem Tod?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["09_Parker.mp3"] = [{
    text: "9. George Parker. George Parker war ein sehr mutiger und selbstbewusster Betrüger, der in New York City lebte. Von den 1880er bis in die 1920er Jahre verdiente er seinen Lebensunterhalt damit, berühmte öffentliche Denkmäler an reiche Besucher zu verkaufen. Sein absoluter Liebling war die schöne und berühmte Brooklyn Bridge. Er fälschte sehr gute Regierungsdokumente, um zu beweisen, dass er die riesige Brücke besaß. Er fand reiche Touristen und verkaufte ihnen die Brücke für Tausende Dollar. Die Touristen merkten erst, dass es ein schlimmer Trick war, als die Stadtpolizei sie stoppte, weil sie Kassen auf der Brücke bauen wollten! Parker verkaufte auch erfolgreich andere berühmte Orte wie den Madison Square Garden und die riesige Freiheitsstatue. Er war sehr charmant, trug schöne Kleidung und sprach gut, sodass die Leute seine verrückten Geschichten leicht glaubten. Die Polizei verhaftete ihn viele Male über die Jahre. Immer, wenn er frei war, versuchte er es wieder. Schließlich wurde ein Richter seine endlosen Lügen leid und schickte ihn für den Rest seines Lebens ins Gefängnis. Er starb hinter Gittern, weit weg von der Brücke.",
    dict: { "mutiger":"cesur", "lebte":"yaşadı", "verdiente":"kazandı", "lebensunterhalt":"geçim", "öffentliche":"kamu/açık", "denkmäler":"anıtlar", "besucher":"ziyaretçiler", "liebling":"favori/sevgili", "brücke":"köprü", "regierungsdokumente":"hükümet belgeleri", "beweisen":"kanıtlamak", "riesige":"devasa", "besaß":"sahipti", "touristen":"turistler", "tausende":"binlerce", "dollar":"dolar", "merkten":"fark ettiler", "schlimmer":"kötü", "stadtpolizei":"şehir polisi", "stoppte":"durdurdu", "kassen":"gişeler/kasalar", "bauen":"inşa etmek", "erfolgreich":"başarılı", "orte":"yerler", "freiheitsstatue":"özgürlük heykeli", "charmant":"büyüleyici/çekici", "kleidung":"kıyafet", "verrückten":"çılgın", "leicht":"kolayca", "verhaftete":"tutukladı", "leid":"bıkmış/yorulmuş", "gittern":"parmaklıklar (hinter Gittern: parmaklıklar ardında)" },
    questions: [ {q:"Lebte George Parker in London?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verkaufte er berühmte Denkmäler an Touristen?", a_de:"Ja", a_tr:"Evet"}, {q:"War die Brooklyn Bridge sein Lieblingsobjekt?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollten Touristen Kassen auf der Brücke bauen?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte er auch die Freiheitsstatue?", a_de:"Ja", a_tr:"Evet"}, {q:"Glaubten die Leute seine Geschichten nicht?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starb er im Gefängnis?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["10_Leviev.mp3"] = [{
    text: "10. Simon Leviev. Simon Leviev ist ein moderner Betrüger, der das Internet nutzte, um viel Geld zu stehlen. Sein richtiger Name ist Shimon Hayut. Er benutzte die beliebte Dating-App Tinder, um einsame Frauen kennenzulernen. Er erzählte ihnen, er sei der reiche Sohn eines berühmten Diamanten-Milliardärs. Er nahm die Frauen mit in teure Privatjets und wohnte in den besten Luxushotels, um zu beweisen, wie wohlhabend er sei. Nachdem die Frauen sich in ihn verliebt hatten, startete er seinen grausamen Plan. Er schickte ihnen gruselige Fotos seines Bodyguards mit blutigem Kopf. Er sagte, seine gefährlichen Feinde griffen ihn an und er könne seine Kreditkarten nicht sicher nutzen. Er flehte die Frauen an, Geld zu leihen, um sein Leben zu retten. Die besorgten Frauen nahmen hohe Bankkredite auf, um dem Mann zu helfen, den sie liebten. Er nutzte ihr Geld zum Reisen und um neue Opfer zu finden. Er stahl Millionen Dollar, bevor die Polizei ihn endlich erwischte. Seine Opfer zahlen bis heute die riesigen Bankkredite zurück, während er frei lebt.",
    dict: { "moderner":"modern", "nutzte":"kullandı", "richtiger":"gerçek/doğru", "dating-app":"arkadaşlık uygulaması", "einsame":"yalnız", "frauen":"kadınlar", "kennenzulernen":"tanışmak", "sohn":"oğul", "diamanten":"elmas", "milliardärs":"milyarder", "privatjets":"özel jetler", "wohlhabend":"varlıklı", "verliebt":"aşık", "startete":"başlattı", "grausamen":"zalim", "schickte":"gönderdi", "gruselige":"korkutucu", "fotos":"fotoğraflar", "bodyguards":"koruma", "blutigem":"kanlı", "kopf":"baş/kafa", "feinde":"düşmanlar", "griffen":"saldırdılar", "kreditkarten":"kredi kartları", "sicher":"güvenli", "flehte":"yalvardı", "leihen":"ödünç almak/vermek", "besorgten":"endişeli", "bankkredite":"banka kredileri", "opfer":"kurbanlar", "finden":"bulmak", "erwischte":"yakaladı", "zahlen":"ödüyorlar", "während":"iken/sırasında", "frei":"özgür" },
    questions: [ {q:"Benutzte Simon Leviev die App Tinder?", a_de:"Ja", a_tr:"Evet"}, {q:"Ist sein richtiger Name Shimon Hayut?", a_de:"Ja", a_tr:"Evet"}, {q:"Sagte er, er sei der Sohn eines Milliardärs?", a_de:"Ja", a_tr:"Evet"}, {q:"Schickte er den Frauen Fotos von seinem Bodyguard?", a_de:"Ja", a_tr:"Evet"}, {q:"Brauchte er das Geld wirklich für seine Sicherheit?", a_de:"Nein", a_tr:"Hayır"}, {q:"Haben die Frauen ihm freiwillig ihr eigenes Geld geschenkt?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zahlen die Opfer heute noch die Kredite zurück?", a_de:"Ja", a_tr:"Evet"} ]
}];lessonData["11_Chadwick.mp3"] = [{
    text: "11. Cassie Chadwick. Cassie Chadwick war eine Expertin darin, Banken zu täuschen und ihr Geld zu stehlen. Ende des 19. Jahrhunderts war Andrew Carnegie einer der reichsten und berühmtesten Männer der Welt. Cassie erfand einen sehr cleveren und einfachen Plan. Sie fälschte ein Papier, das sie als Andrew Carnegies geheime Tochter auswies. Sie fälschte auch Dokumente, die besagten, Carnegie habe ihr Millionen gegeben, um sie zum Schweigen zu bringen. Sie zeigte diese Papiere vielen Bankmanagern in Amerika. Damals wollten Banker einen berühmten, reichen und mächtigen Mann wie Carnegie nicht stören, um nachzufragen, ob die Geschichte stimmte. Sie glaubten einfach Cassies Lügen. Die Banken gaben ihr gerne hohe Kredite. Sie kaufte funkelnde Diamanten, schöne teure Kleidung und schwere Goldketten. Sie stahl etwa zwei Millionen Dollar – das entspricht heute etwa 60 Millionen. Sie lebte jahrelang wie eine echte Königin. Schließlich fragte ein mutiger Bankmanager Andrew Carnegie nach ihr. Er sagte, er kenne sie gar nicht. Die Polizei verhaftete sie, und sie starb ein paar Jahre später im Gefängnis.",
    dict: { "expertin":"uzman", "täuschen":"kandırmak", "stehlen":"çalmak", "jahrhunderts":"yüzyıl", "reichsten":"en zengin", "erfand":"icat etti", "cleveren":"zeki", "einfachen":"basit", "plan":"plan", "fälschte":"sahtesini yaptı", "papier":"kağıt/belge", "geheime":"gizli", "tochter":"kız evlat", "auswies":"gösteren/tanımlayan", "dokumente":"belgeler", "besagten":"belirten", "millionen":"milyonlar", "schweigen":"sessizlik", "bringen":"getirmek (zum Schweigen bringen: susturmak)", "zeigte":"gösterdi", "bankmanagern":"banka yöneticileri", "mächtigen":"güçlü", "stören":"rahatsız etmek", "nachzufragen":"sormak/soruşturmak", "stimmte":"doğruydu", "glaubten":"inandılar", "kredite":"krediler", "kaufte":"satın aldı", "funkelnde":"parıldayan", "diamanten":"elmaslar", "kleidung":"kıyafet", "goldketten":"altın kolyeler", "entspricht":"karşılık gelir", "königin":"kraliçe", "kenne":"tanımak", "starb":"öldü" },
    questions: [ {q:"War Cassie Chadwick eine Expertin im Täuschen von Banken?", a_de:"Ja", a_tr:"Evet"}, {q:"Sagte sie, sie sei die geheime Tochter von Andrew Carnegie?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte sie echte Dokumente von Carnegie?", a_de:"Nein", a_tr:"Hayır"}, {q:"Glaubten die Banker ihre Lügen ohne nachzufragen?", a_de:"Ja", a_tr:"Evet"}, {q:"Kaufte sie von dem Geld teure Goldketten und Diamanten?", a_de:"Ja", a_tr:"Evet"}, {q:"Kannte Andrew Carnegie sie wirklich?", a_de:"Nein", a_tr:"Hayır"}, {q:"Starb sie als reiche Frau in Freiheit?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["12_McFarland.mp3"] = [{
    text: "12. Billy McFarland. Billy McFarland versprach, die beste und teuerste Musikparty der Welt zu veranstalten, schuf aber eine riesige Katastrophe. Er organisierte 2017 das berühmte Fyre Festival. Er bezahlte schöne Models, um auf Instagram atemberaubende Fotos einer sonnigen Insel auf den Bahamas zu posten. Er versprach Luxus-Strandzelte, tolles teures Essen und die besten Musikbands der Welt. Reiche junge Leute zahlten Tausende Dollar für Tickets. Aber McFarland wusste nicht, wie man ein echtes Festival organisiert, und ihm ging schnell das Geld aus. Er log alle an. Als die aufgeregten Gäste auf der Insel ankamen, gab es keine Luxuszelte. Sie mussten in nassen, schmutzigen Notzelten schlafen. Es gab kein gutes Essen, nur einfache kalte Käse-Sandwiches in billigen Boxen. Die berühmten Bands kamen nicht. Es war ein totales Desaster, und die Leute saßen auf der Insel fest ohne Rückflüge. Die Polizei verhaftete McFarland wegen Betrugs. Ein Richter schickte ihn für vier Jahre ins Gefängnis, weil er Geld gestohlen und Tausende angelogen hatte.",
    dict: { "versprach":"söz verdi", "teuerste":"en pahalı", "veranstalten":"düzenlemek", "schuf":"yarattı", "riesige":"devasa", "katastrophe":"felaket", "organisierte":"organize etti", "atemberaubende":"nefes kesici", "sonnige":"güneşli", "insel":"ada", "luxus-strandzelte":"lüks plaj çadırları", "essen":"yemek", "musikbands":"müzik grupları", "tickets":"biletler", "echtes":"gerçek", "schnell":"hızlı", "aufgeregten":"heyecanlı", "gäste":"misafirler", "ankamen":"vardılar", "nassen":"ıslak", "schmutzigen":"kirli", "notzelten":"acil durum çadırları", "schlafen":"uyumak", "käse-sandwiches":"peynirli sandviçler", "billigen":"ucuz", "boxen":"kutular", "desaster":"felaket", "saßen":"oturdular/kaldılar (saßen fest: mahsur kaldılar)", "rückflüge":"dönüş uçuşları", "betrugs":"dolandırıcılık", "angelogen":"yalan söyledi" },
    questions: [ {q:"Organisierte Billy McFarland das Fyre Festival?", a_de:"Ja", a_tr:"Evet"}, {q:"Gab es auf der Insel wirklich Luxus-Strandzelte?", a_de:"Nein", a_tr:"Hayır"}, {q:"Zahlten reiche junge Leute viel Geld für Tickets?", a_de:"Ja", a_tr:"Evet"}, {q:"War das Essen auf der Insel sehr gut?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kamen die berühmten Musikbands zum Festival?", a_de:"Nein", a_tr:"Hayır"}, {q:"Saßen die Leute auf der Insel fest?", a_de:"Ja", a_tr:"Evet"}, {q:"Kam McFarland wegen Betrugs ins Gefängnis?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["13_Voigt.mp3"] = [{
    text: "13. Wilhelm Voigt. Wilhelm Voigt war 1906 ein armer, alter Schuhmacher in Deutschland. Er war schon im Gefängnis gewesen und fand keinen guten Job. Er merkte, dass die Deutschen Militäruniformen zu sehr respektierten und immer Befehle befolgten. Also kaufte er langsam Teile einer Hauptmannsuniform in verschiedenen Secondhand-Läden. Er zog die alte Uniform an und ging stolz die Straße entlang. Er sah eine Gruppe echter, müder Soldaten und befahl ihnen, ihm zu folgen. Weil er eine Hauptmannsuniform trug, gehorchten sie ohne Fragen! Er marschierte mit ihnen zum Rathaus. Er sagte dem Bürgermeister, er sei verhaftet wegen eines geheimen Verbrechens. Dann nahm er selbstbewusst all das Geld aus dem Stadtsafe. Er befahl den Soldaten, den Bürgermeister zu bewachen, und ging einfach mit dem Bargeld davon! Als die Polizei ihn endlich erwischte, stand die Geschichte in allen Zeitungen. Sogar der deutsche Kaiser lachte laut über seinen cleveren Trick. Der Kaiser begnadigte ihn sogar frühzeitig, weil der Scherz für das ganze Land so lustig war.",
    dict: { "armer":"fakir", "schuhmacher":"ayakkabı tamircisi", "deutschland":"almanya", "job":"iş", "merkte":"fark etti", "militäruniformen":"askeri üniformalar", "respektierten":"saygı duydular", "befehle":"emirler", "befolgten":"uydular", "langsam":"yavaşça", "hauptmannsuniform":"yüzbaşı üniforması", "secondhand-läden":"ikinci el dükkanlar", "zog":"giydi (zog an)", "stolz":"gururla", "entlang":"boyunca", "müder":"yorgun", "soldaten":"askerler", "befahl":"emretti", "folgen":"takip etmek", "trug":"giydi", "gehorchten":"itaat ettiler", "marschierte":"yürüdü", "rathaus":"belediye binası", "bürgermeister":"belediye başkanı", "verhaftet":"tutuklu", "stadtsafe":"şehir kasası", "bewachen":"korumak/gözetlemek", "bargeld":"nakit para", "davon":"oradan (davongehen: çekip gitmek)", "kaiser":"imparator", "lachte":"güldü", "cleveren":"zeki", "begnadigte":"affetti", "frühzeitig":"erken", "scherz":"şaka" },
    questions: [ {q:"War Wilhelm Voigt ein reicher Soldat?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kaufte er sich eine Hauptmannsuniform?", a_de:"Ja", a_tr:"Evet"}, {q:"Gehorchten die echten Soldaten ihm?", a_de:"Ja", a_tr:"Evet"}, {q:"Marschierte er mit den Soldaten zum Rathaus?", a_de:"Ja", a_tr:"Evet"}, {q:"Stahl er Geld aus dem Stadtsafe?", a_de:"Ja", a_tr:"Evet"}, {q:"War der deutsche Kaiser sehr wütend über den Trick?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde Voigt vom Kaiser begnadigt?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["14_Valois.mp3"] = [{
    text: "14. Jeanne de Valois-Saint-Rémy. Jeanne war eine arme Frau, die in den 1780er Jahren in Frankreich lebte. Sie wollte sehr reich werden und ein luxuriöses Leben am königlichen Hof führen. Sie hörte von einer sehr teuren Diamantenhalskette, die Königin Marie Antoinette nicht kaufen wollte. Jeanne erfand einen brillanten und bösen Plan, um sie zu stehlen. Sie erzählte einem reichen Kardinal, sie sei die geheime beste Freundin der Königin. Sie sagte ihm, die Königin wolle die Kette heimlich, könne sie aber nicht selbst kaufen. Jeanne heuerte sogar eine arme Frau an, die der Königin genau glich, um den Kardinal nachts in einem dunklen Garten zu treffen. Der Kardinal glaubte dem cleveren Trick vollkommen. Er kaufte die schöne Kette und gab sie Jeanne. Jeannes Ehemann brachte die Kette nach London und verkaufte die Diamanten für viel Bargeld. Als der Kardinal die Königin endlich nach dem Geld fragte, kam das schreckliche Geheimnis ans Licht. Die Polizei verhaftete Jeanne, aber die Leute hassten die Königin so sehr, dass dieser riesige Skandal tatsächlich half, die berühmte und blutige Französische Revolution auszulösen!",
    dict: { "luxuriöses":"lüks", "königlichen":"kraliyet", "hof":"saray", "führen":"sürdürmek", "diamantenhalskette":"elmas kolye", "königin":"kraliçe", "brillanten":"dahice", "bösen":"kötü", "kardinal":"kardinal", "geheime":"gizli", "heimlich":"gizlice", "heuerte":"kiraladı (heuerte an)", "genau":"tamamen", "glich":"benziyordu", "nachts":"geceleri", "garten":"bahçe", "treffen":"buluşmak", "ehemann":"koca", "brachte":"getirdi", "licht":"ışık (ans Licht kommen: açığa çıkmak)", "hassten":"nefret ettiler", "skandal":"skandal", "blutige":"kanlı", "revolution":"devrim", "auszulösen":"başlatmak/tetiklemek" },
    questions: [ {q:"Lebte Jeanne in Frankreich?", a_de:"Ja", a_tr:"Evet"}, {q:"Wollte Marie Antoinette die Kette wirklich kaufen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Täuschte Jeanne einen reichen Kardinal?", a_de:"Ja", a_tr:"Evet"}, {q:"Heuerte Jeanne eine Frau an, die wie die Königin aussah?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte Jeannes Ehemann die Diamanten in Paris?", a_de:"Nein", a_tr:"Hayır"}, {q:"Kam das Geheimnis am Ende ans Licht?", a_de:"Ja", a_tr:"Evet"}, {q:"Half der Skandal, die Revolution auszulösen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["15_Ferguson.mp3"] = [{
    text: "15. Arthur Ferguson. Arthur Ferguson war ein schottischer Schauspieler, der seine tollen Schauspielfähigkeiten nutzte, um ein großer Betrüger zu werden. Nach dem Ersten Weltkrieg besuchten viele reiche amerikanische Touristen London, um die Sehenswürdigkeiten zu sehen. Ferguson stand am Trafalgar Square und suchte wohlhabende Touristen. Er tat so, als wäre er ein sehr wichtiger und seriöser Regierungsbeamter. Er erzählte den Amerikanern, die britische Regierung sei nach dem langen Krieg sehr arm. Sie verkaufe heimlich berühmte öffentliche Denkmäler, um das Land vor dem Ruin zu retten. Erstaunlicherweise verkaufte er die berühmte Nelson-Säule an einen Amerikaner für viel Geld. Später verkaufte er Big Ben, den berühmten Glockenturm, an einen anderen Touristen. Er nahm sogar eine riesige Anzahlung für den Buckingham Palace! Er war so selbstbewusst, dass niemand Verdacht schöpfte. Später zog er nach Amerika und versuchte, das berühmte Weiße Haus an einen reichen Farmer zu verkaufen. Schließlich verhaftete ihn die Polizei und er kam wegen seiner Verbrechen ins Gefängnis. Er bewies, dass ein guter Schauspieler Menschen fast alles glauben machen kann.",
    dict: { "schauspieler":"oyuncu", "schauspielfähigkeiten":"oyunculuk yetenekleri", "ersten":"birinci", "weltkrieg":"dünya savaşı", "besuchten":"ziyaret ettiler", "touristen":"turistler", "sehenswürdigkeiten":"turistik yerler", "wohlhabende":"varlıklı", "regierungsbeamter":"hükümet yetkilisi", "britische":"ingiliz", "regierung":"hükümet", "denkmäler":"anıtlar", "retten":"kurtarmak", "nelson-säule":"nelson sütunu", "glockenturm":"saat kulesi", "anzahlung":"kaparo/ön ödeme", "palace":"saray", "selbstbewusst":"özgüvenli", "verdacht":"şüphe", "schöpfte":"hissetti/oluşturdu (Verdacht schöpfen: şüphelenmek)", "weiße":"beyaz", "haus":"ev", "farmer":"çiftçi", "verhaftete":"tutukladı", "bewies":"kanıtladı" },
    questions: [ {q:"War Arthur Ferguson ein schottischer Schauspieler?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte er die Nelson-Säule in London?", a_de:"Ja", a_tr:"Evet"}, {q:"War die britische Regierung wirklich arm?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verkaufte er auch den Big Ben?", a_de:"Ja", a_tr:"Evet"}, {q:"Schöpften die Touristen sofort Verdacht?", a_de:"Nein", a_tr:"Hayır"}, {q:"Versuchte er, das Weiße Haus in Amerika zu verkaufen?", a_de:"Ja", a_tr:"Evet"}, {q:"Kam er am Ende ins Gefängnis?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["16_Pearlman.mp3"] = [{
    text: "16. Lou Pearlman. Lou Pearlman war in den 1990er Jahren sehr berühmt dafür, große Pop-Gruppen wie die Backstreet Boys und NSYNC zu gründen. Er wirkte wie ein sehr erfolgreicher, glücklicher und reicher Musikmanager. Er kaufte riesige Häuser, teure Autos und flog in Privatjets um die Welt. Aber er hatte ein sehr dunkles und gieriges Geheimnis. Zuerst stahl er fast das gesamte Geld seiner jungen Musikstars. Er ließ sie als Teenager sehr schlechte und ungerechte Verträge unterschreiben. Zweitens betrieb er im Hintergrund ein massives Ponzi-Schema. Er erfand komplett gefälschte Firmen und Banken. Er bat normale Leute, in seine Geschäfte zu investieren, und versprach schnelles viel Geld. Er stahl etwa 300 Millionen Dollar von Freunden, Familie und normalen Menschen. Als die Polizei seine gefälschten Firmen untersuchte, floh er nach Indonesien. Das FBI erwischte ihn, und ein Richter gab ihm 25 Jahre Haft. Er starb allein im Gefängnis, weit weg vom Rampenlicht und der lauten Musik seiner berühmten Vergangenheit.",
    dict: { "gründen":"kurmak", "wirkte":"görünüyordu", "erfolgreicher":"başarılı", "glücklicher":"mutlu", "musikmanager":"müzik menajeri", "riesige":"devasa", "häuser":"evler", "autos":"arabalar", "flog":"uçtu", "privatjets":"özel jetler", "gieriges":"açgözlü", "geheimnis":"sır", "zuerst":"ilk olarak", "stahl":"çaldı", "gesamte":"tüm", "musikstars":"müzik yıldızları", "schlechte":"kötü", "ungerechte":"adaletsiz", "verträge":"sözleşmeler", "unterschreiben":"imzalamak", "hintergrund":"arka plan", "erfand":"icat etti", "gefälschte":"sahte", "firmen":"şirketler", "geschäfte":"işler", "investieren":"yatırım yapmak", "versprach":"söz verdi", "familie":"aile", "untersuchte":"inceledi", "floh":"kaçı", "erwischte":"yakaladı", "haft":"hapis", "allein":"yalnız", "rampenlicht":"spot ışığı", "vergangenheit":"geçmiş" },
    questions: [ {q:"Gründete Lou Pearlman die Backstreet Boys?", a_de:"Ja", a_tr:"Evet"}, {q:"War er ein ehrlicher Musikmanager?", a_de:"Nein", a_tr:"Hayır"}, {q:"Unterschrieben die Musikstars sehr gute Verträge?", a_de:"Nein", a_tr:"Hayır"}, {q:"Betrieb er ein massives Ponzi-Schema?", a_de:"Ja", a_tr:"Evet"}, {q:"Stahl er etwa 300 Millionen Dollar?", a_de:"Ja", a_tr:"Evet"}, {q:"Floh er nach Indonesien?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb er als reicher Mann in Freiheit?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["17_Valfierno.mp3"] = [{
    text: "17. Eduardo de Valfierno. Eduardo de Valfierno ist berühmt für ein Verbrechen, das vielleicht ein Mythos ist, aber eine geniale und clevere Geschichte. Er nannte sich selbst einen wohlhabenden Marquis. Im Jahr 1911 wurde das berühmte Gemälde Mona Lisa aus dem Louvre in Paris gestohlen. Ein stiller Mann namens Vincenzo Peruggia stahl es tatsächlich. Aber Jahre später erzählte Valfierno einem Reporter, er sei der wahre Drahtzieher gewesen. Valfierno sagte, er habe nie vorgehabt, das echte Gemälde zu verkaufen. Vor dem großen Diebstahl bezahlte er einen exzellenten Künstler, sechs perfekte Kopien der Mona Lisa zu malen. Als das echte Bild gestohlen war, stand es in allen Zeitungen der Welt. Valfierno traf sich dann heimlich mit sechs verschiedenen reichen Käufern. Er verkaufte ihnen seine sechs Fälschungen für riesige Summen. Er sagte jedem Käufer, er bekomme das echte gestohlene Bild! Er machte Millionen und ließ den echten Dieb die ganze Schuld und das Gefängnis tragen. Es war ein perfektes Verbrechen, weil die reichen Käufer nie der Polizei sagen konnten, sie hätten gestohlene Kunst gekauft.",
    dict: { "vielleicht":"belki", "mythos":"mit/efsane", "geniale":"dahice", "selbst":"kendini", "wohlhabenden":"varlıklı", "marquis":"marki", "gemälde":"tablo", "gestohlen":"çalınmış", "stiller":"sessiz", "namens":"adında", "tatsächlich":"aslında", "später":"sonra", "erzählte":"anlattı", "wahre":"gerçek", "drahtzieher":"elebaşı", "vorgehabt":"niyetlenmiş", "echte":"gerçek", "verkaufen":"satmak", "diebstahl":"hırsızlık", "bezahlte":"ödedi", "exzellenten":"mükemmel", "künstler":"sanatçı", "perfekte":"kusursuz", "kopien":"kopyalar", "malen":"boyamak", "zeitungen":"gazeteler", "heimlich":"gizlice", "verschiedenen":"farklı", "käufern":"alıcılar", "fälschungen":"sahteler", "summen":"meblağlar", "bekomme":"aldığını", "dieb":"hırsız", "schuld":"suç/borç", "tragen":"taşımak", "kunst":"sanat" },
    questions: [ {q:"Wurde die Mona Lisa im Jahr 1911 aus dem Louvre gestohlen?", a_de:"Ja", a_tr:"Evet"}, {q:"Stahl Valfierno das Bild mit seinen eigenen Händen?", a_de:"Nein", a_tr:"Hayır"}, {q:"Ließ er sechs Kopien der Mona Lisa malen?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte er das echte Bild an sechs verschiedene Käufer?", a_de:"Nein", a_tr:"Hayır"}, {q:"Verkaufte er die sechs Kopien als das echte Bild?", a_de:"Ja", a_tr:"Evet"}, {q:"Machte er damit Millionen Dollar?", a_de:"Ja", a_tr:"Evet"}, {q:"Gingen die reichen Käufer am Ende zur Polizei?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["18_Marco.mp3"] = [{
    text: "18. Enric Marco. Enric Marco war ein Mann aus Spanien, der eine schreckliche und traurige Lüge erzählte, nur um Aufmerksamkeit und Respekt zu bekommen. Viele Jahre lang war er Präsident einer großen Gruppe für Holocaust-Überlebende in Spanien. Er hielt hunderte emotionale Reden vor Schulen, Lehrern und Politikern. Er weinte echte Tränen, während er traurige Geschichten von seiner schweren Zeit im Nazi-KZ Flossenbürg im Zweiten Weltkrieg erzählte. Die Leute hielten ihn für einen großen und mutigen Helden. Er bekam sogar eine besondere Goldmedaille von der spanischen Regierung. Aber 2005 schaute ein kluger Historiker in die echten Kriegsdokumente. Der Historiker entdeckte eine schockierende Wahrheit. Marco war nie in einem Konzentrationslager! Er war tatsächlich als normaler Freiwilliger nach Deutschland gegangen, nicht als Gefangener. Er erfand die ganze traurige Geschichte nur, weil er bewundert werden und gehört werden wollte. Er musste seine besondere Medaille zurückgeben und lebte den Rest seines Lebens in großer Schande wegen seiner schrecklichen Lügen.",
    dict: { "spanien":"ispanya", "schreckliche":"korkunç", "traurige":"üzücü", "lüge":"yalan", "aufmerksamkeit":"ilgi", "respekt":"saygı", "präsident":"başkan", "gruppe":"grup", "holocaust-überlebende":"holokost kurtulanları", "hielt":"yaptı/tuttu (Reden halten: konuşma yapmak)", "emotionale":"duygusal", "reden":"konuşmalar", "schulen":"okullar", "lehrern":"öğretmenler", "politikern":"politikacılar", "weinte":"ağladı", "tränen":"gözyaşları", "helden":"kahraman", "goldmedaille":"altın madalya", "schaute":"baktı", "historiker":"tarihçi", "entdeckte":"keşfetti", "schockierende":"şok edici", "wahrheit":"gerçek", "konzentrationslager":"toplama kampı", "freiwilliger":"gönüllü", "gefangener":"esir", "bewundert":"hayran olunan", "gehört":"duyulmuş", "zurückgeben":"geri vermek", "schande":"utanç" },
    questions: [ {q:"War Enric Marco ein Präsident für Holocaust-Überlebende?", a_de:"Ja", a_tr:"Evet"}, {q:"Hielt er emotionale Reden vor Schulen?", a_de:"Ja", a_tr:"Evet"}, {q:"War er wirklich im Nazi-KZ Flossenbürg?", a_de:"Nein", a_tr:"Hayır"}, {q:"Bekam er eine Goldmedaille von der Regierung?", a_de:"Ja", a_tr:"Evet"}, {q:"Entdeckte ein Historiker die Wahrheit?", a_de:"Ja", a_tr:"Evet"}, {q:"War er ein Gefangener im Zweiten Weltkrieg?", a_de:"Nein", a_tr:"Hayır"}, {q:"Lebte er am Ende in Schande?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["19_Rocancourt.mp3"] = [{
    text: "19. Christophe Rocancourt. Christophe Rocancourt war ein armer Junge aus einer kleinen Stadt in Frankreich, wurde aber ein Meister der falschen Identitäten. In den 1990er Jahren zog er nach Los Angeles in Amerika. Er wollte Teil des reichen und berühmten Hollywood-Lebens werden. Also erzählte er den Leuten, er sei ein junger Mitglied der berühmten und reichen Rockefeller-Familie. Er trug sehr teure Anzüge, trank den besten Wein und fuhr unglaublich schnelle Autos. Er war sehr charmant und wurde schnell Freund von berühmten Filmschauspielern und reichen Geschäftsleuten. Er sagte seinen neuen reichen Freunden, er könne ihr Geld verdoppeln, wenn sie in seine geheimen Geschäfte investierten. Natürlich gab es gar keine echten Geschäfte. Er nahm ihr Geld nur, um sein eigenes Luxusleben zu finanzieren. Er stahl Millionen von Leuten, die ihn für ein Genie hielten. Die Polizei erwischte ihn schließlich in Kanada, wo er sich versteckte. Er kam ins Gefängnis, schrieb aber später ein populäres Buch über seine tollen Verbrechen. In Frankreich wurde er sogar ziemlich berühmt dafür, so ein cleverer Dieb zu sein.",
    dict: { "junge":"çocuk/genç", "kleinen":"küçük", "stadt":"şehir", "meister":"usta", "identitäten":"kimlikler", "zog":"taşındı", "reich":"zengin", "berühmt":"ünlü", "mitglied":"üye", "anzüge":"takım elbiseler", "trank":"içti", "wein":"şarap", "schnelle":"hızlı", "autos":"arabalar", "freund":"arkadaş", "verdoppeln":"ikiye katlamak", "natürlich":"tabii ki", "luxusleben":"lüks yaşam", "finanzieren":"finanse etmek", "kanada":"kanada", "versteckte":"gizlendi", "populäres":"popüler", "buch":"kitap", "cleverer":"zeki", "dieb":"hırsız" },
    questions: [ {q:"Ist Christophe Rocancourt in Amerika geboren?", a_de:"Nein", a_tr:"Hayır"}, {q:"Sagte er, er sei ein Mitglied der Rockefeller-Familie?", a_de:"Ja", a_tr:"Evet"}, {q:"Trug er teure Anzüge ve trank guten Wein?", a_de:"Ja", a_tr:"Evet"}, {q:"Hatte er echte Geschäfte, um Geld zu verdoppeln?", a_de:"Nein", a_tr:"Hayır"}, {q:"Stahl er Millionen von reichen Leuten?", a_de:"Ja", a_tr:"Evet"}, {q:"Erwischte die Polizei ihn in Kanada?", a_de:"Ja", a_tr:"Evet"}, {q:"Schrieb er ein Buch über seine Verbrechen?", a_de:"Ja", a_tr:"Evet"} ]
}];

lessonData["20_Soapy.mp3"] = [{
    text: "20. Soapy Smith. Soapy Smith war ein berühmter und sehr cleverer Betrüger im amerikanischen „Wilden Westen“ der 1800er Jahre. Sein richtiger Name war Jefferson Randolph Smith. Er bekam seinen lustigen Spitznamen „Soapy“ wegen seines Lieblingstricks auf der Straße. Er stand auf der schmutzigen Straße mit einer großen Menge Zuschauern. Er wickelte normale, billige Seifenstücke in Papier. Aber er ließ die Menge klar sehen, wie er ein paar Stücke mit 100-Dollar-Scheinen einwickelte. Er mischte alle Seifen in einer Tasche und verkaufte sie für je einen Dollar. Arme Leute kauften die Seife in der Hoffnung auf das große Geld. Aber Smith nutzte sehr schnelle Zaubertricks. Er nahm heimlich das Geld heraus oder ließ seine geheimen Freunde in der Menge die Gewinner-Seife kaufen. Die normalen Leute bekamen nur normale Seife. Später in seinem Leben zog er während des berühmten Goldrausches nach Alaska. Er kontrollierte eine ganze Stadt mit seiner großen kriminellen Bande. Er betrieb gefälschte Telegrafenbüros und manipulierte Kartenspiele, bis er schließlich in einem berühmten Schusswechsel auf den Docks getötet wurde.",
    dict: { "wilden":"vahşi", "westen":"batı", "richtiger":"gerçek", "lustigen":"komik", "spitznamen":"takma ad", "seifenstücke":"sabun kalıpları", "papier":"kağıt", "menge":"kalabalık/miktar", "zuschauern":"izleyiciler", "wickelte":"sardı", "scheinen":"banknotlar (100-Dollar-Scheinen)", "mischte":"karıştırdı", "tasche":"çanta", "hoffnung":"umut", "zaubertricks":"sihirbazlık numaraları", "heraus":"dışarı (herausnehmen: çıkarmak)", "gewinner-seife":"kazanan sabun", "goldrausches":"altına hücum", "alaska":"alaska", "kontrollierte":"kontrol etti", "kriminelle":"suçlu", "bande":"çete", "betrieb":"işletti", "telegrafenbüros":"telgraf ofisleri", "manipulierte":"manipüle etti", "kartenspiele":"kart oyunları", "schusswechsel":"çatışma", "docks":"rıhtımlar", "getötet":"öldürüldü" },
    questions: [ {q:"War Jefferson Randolph Smith sein richtiger Name?", a_de:"Ja", a_tr:"Evet"}, {q:"Wickelte er Geld in Seifenstücke ein?", a_de:"Ja", a_tr:"Evet"}, {q:"Gewannen die armen Leute oft das große Geld?", a_de:"Nein", a_tr:"Hayır"}, {q:"Nutzte Smith Zaubertricks für seinen Betrug?", a_de:"Ja", a_tr:"Evet"}, {q:"Zog er später nach Alaska?", a_de:"Ja", a_tr:"Evet"}, {q:"Kontrollierte er eine Stadt mit einer Čete?", a_de:"Ja", a_tr:"Evet"}, {q:"Starb er friedlich im Alter?", a_de:"Nein", a_tr:"Hayır"} ]
}];

lessonData["21_Natwarlal.mp3"] = [{
    text: "21. Natwarlal. Natwarlal war Indiens berühmtester und cleverster Betrüger. Ursprünglich war er ein kluger Anwalt, merkte aber, dass er sehr gut darin war, die Handschrift und Unterschriften anderer zu fälschen. Er nutzte diese besondere Fähigkeit, um viel Geld von großen Banken und reichen Firmen zu stehlen. Er war ein Meister der Verkleidung und wechselte oft Kleidung und Gesicht, um der Polizei zu entkommen. Aber seine berühmtesten und lustigsten Verbrechen waren, öffentliche Denkmäler an Ausländer zu verkaufen. Er tat so, als wäre er ein wichtiger Regierungsbeamter. Er fand reiche ausländische Touristen und „verkaufte“ ihnen den wunderschönen Taj Mahal! Er tat das tatsächlich dreimal. Er verkaufte auch erfolgreich das riesige Rote Fort und das sehr wichtige indische Parlamentsgebäude. Er wurde viele Male verhaftet, und Richter gaben ihm insgesamt 113 Jahre Gefängnis. Aber er war ein Experte im Ausbrechen aus dem Gefängnis. Er entkam neunmal. Beim letzten Mal war er 84 Jahre alt und saß im Rollstuhl! Niemand hat ihn je wieder gesehen.",
    dict: { "indien":"hindistan", "cleverster":"en zeki", "ursprünglich":"başlangıçta", "anwalt":"avukat", "handschrift":"el yazısı", "unterschriften":"imzalar", "fälschen":"taklit etmek", "fähigkeit":"yetenek", "firmen":"şirketler", "verkleidung":"kılık değiştirme", "gesicht":"yüz", "entkommen":"kaçmak", "verbrechen":"suçlar", "ausländer":"yabancılar", "taj-mahal":"tac mahal", "dreimal":"üç kez", "rote":"kırmızı", "fort":"kale", "parlamentsgebäude":"parlamento binası", "insgesamt":"toplamda", "ausbrechen":"kaçmak/firar etmek", "entkam":"kaçtı", "neunmal":"dokuz kez", "rollstuhl":"tekerlekli sandalye", "niemand":"hiç kimse" },
    questions: [ {q:"War Natwarlal ein berühmter Betrüger in Indien?", a_de:"Ja", a_tr:"Evet"}, {q:"Konnte er Unterschriften perfekt fälschen?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte er den Taj Mahal wirklich?", a_de:"Ja", a_tr:"Evet"}, {q:"Verkaufte er das Parlamentsgebäude nur einmal?", a_de:"Nein", a_tr:"Hayır"}, {q:"Wurde er zu 113 Jahren Gefängnis verurteilt?", a_de:"Ja", a_tr:"Evet"}, {q:"Entkam er neunmal aus dem Gefängnis?", a_de:"Ja", a_tr:"Evet"}, {q:"War er beim letzten Ausbruch 20 Jahre alt?", a_de:"Nein", a_tr:"Hayır"} ]
}];
